package com.lunamax.medassistant;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

import org.json.JSONArray;
import org.json.JSONObject;

import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/** Local store for the complete product model. Free-text fields are encrypted with Android Keystore. */
final class LunaDatabase extends SQLiteOpenHelper {
    private static final String NAME = "luna_max_local.db";
    private static final int VERSION = 4;
    private final SimpleDateFormat dayFormat = new SimpleDateFormat("yyyy-MM-dd", Locale.US);
    private final DataCipher cipher;

    LunaDatabase(Context context) {
        super(context.getApplicationContext(), NAME, null, VERSION);
        cipher = new DataCipher(context);
    }

    @Override public void onCreate(SQLiteDatabase db) { createTables(db); }

    @Override public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        createTables(db);
        addColumn(db, "medication", "generic_name_enc", "TEXT"); addColumn(db, "medication", "brand_name_enc", "TEXT");
        addColumn(db, "medication", "ingredient_enc", "TEXT"); addColumn(db, "medication", "strength_enc", "TEXT");
        addColumn(db, "medication", "dosage_form_enc", "TEXT"); addColumn(db, "medication", "manufacturer_enc", "TEXT");
        addColumn(db, "medication", "approval_no_enc", "TEXT"); addColumn(db, "medication", "indication_enc", "TEXT");
        addColumn(db, "medication", "contraindications_enc", "TEXT"); addColumn(db, "medication", "notes_enc", "TEXT");
        addColumn(db, "medication", "image_uri_enc", "TEXT"); addColumn(db, "medication", "status", "TEXT DEFAULT 'ACTIVE'"); addColumn(db, "medication", "updated_at", "INTEGER DEFAULT 0");
        addColumn(db, "plan", "type", "TEXT DEFAULT 'DAILY'"); addColumn(db, "plan", "times_csv", "TEXT DEFAULT '08:00'"); addColumn(db, "plan", "weekdays_mask", "INTEGER DEFAULT 127");
        addColumn(db, "plan", "interval_hours", "INTEGER DEFAULT 8"); addColumn(db, "plan", "start_date", "TEXT"); addColumn(db, "plan", "end_date", "TEXT"); addColumn(db, "plan", "start_at_ms", "INTEGER DEFAULT 0");
        addColumn(db, "plan", "dose_enc", "TEXT"); addColumn(db, "plan", "meal_enc", "TEXT"); addColumn(db, "plan", "notes_enc", "TEXT"); addColumn(db, "plan", "paused", "INTEGER DEFAULT 0");
        addColumn(db, "occurrence", "planned_at_ms", "INTEGER DEFAULT 0"); addColumn(db, "occurrence", "scheduled_at_ms", "INTEGER DEFAULT 0"); addColumn(db, "occurrence", "action_at_ms", "INTEGER DEFAULT 0");
        addColumn(db, "occurrence", "actual_at_ms", "INTEGER DEFAULT 0"); addColumn(db, "occurrence", "snooze_until_ms", "INTEGER DEFAULT 0"); addColumn(db, "occurrence", "batch_id", "INTEGER DEFAULT 0"); addColumn(db, "occurrence", "user_note_enc", "TEXT");
        addColumn(db, "document", "links_enc", "TEXT");
        addColumn(db, "document", "compressed_uri_enc", "TEXT"); addColumn(db, "document", "compressed_sha256", "TEXT"); addColumn(db, "document", "ai_raw_response_enc", "TEXT"); addColumn(db, "document", "structured_json_enc", "TEXT"); addColumn(db, "document", "prompt_version_enc", "TEXT"); addColumn(db, "document", "model", "TEXT"); addColumn(db, "document", "recognition_status", "TEXT DEFAULT 'LEGACY'"); addColumn(db, "document", "failure_reason_enc", "TEXT"); addColumn(db, "document", "request_at_ms", "INTEGER DEFAULT 0");
        migratePrototypeRows(db);
    }

    private static void createTables(SQLiteDatabase db) {
        db.execSQL("CREATE TABLE IF NOT EXISTS medication (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL DEFAULT '', dose TEXT NOT NULL DEFAULT '', stock INTEGER NOT NULL DEFAULT 0, expiry TEXT, created_at TEXT NOT NULL DEFAULT '', generic_name_enc TEXT, brand_name_enc TEXT, ingredient_enc TEXT, strength_enc TEXT, dosage_form_enc TEXT, manufacturer_enc TEXT, approval_no_enc TEXT, indication_enc TEXT, contraindications_enc TEXT, notes_enc TEXT, image_uri_enc TEXT, status TEXT NOT NULL DEFAULT 'ACTIVE', updated_at INTEGER NOT NULL DEFAULT 0)");
        db.execSQL("CREATE TABLE IF NOT EXISTS batch (id INTEGER PRIMARY KEY AUTOINCREMENT, medication_id INTEGER NOT NULL, lot_no_enc TEXT, quantity REAL NOT NULL DEFAULT 0, quantity_unit_enc TEXT, production_date_enc TEXT, expiry_date_enc TEXT, opened_date_enc TEXT, storage_location_enc TEXT, storage_conditions_enc TEXT, state TEXT NOT NULL DEFAULT 'IN_STOCK', notes_enc TEXT, image_uri_enc TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, FOREIGN KEY(medication_id) REFERENCES medication(id))");
        db.execSQL("CREATE TABLE IF NOT EXISTS plan (id INTEGER PRIMARY KEY AUTOINCREMENT, medication_id INTEGER NOT NULL, time_text TEXT NOT NULL DEFAULT '08:00', enabled INTEGER NOT NULL DEFAULT 1, type TEXT NOT NULL DEFAULT 'DAILY', times_csv TEXT NOT NULL DEFAULT '08:00', weekdays_mask INTEGER NOT NULL DEFAULT 127, interval_hours INTEGER NOT NULL DEFAULT 8, start_date TEXT, end_date TEXT, start_at_ms INTEGER NOT NULL DEFAULT 0, dose_enc TEXT, meal_enc TEXT, notes_enc TEXT, paused INTEGER NOT NULL DEFAULT 0, FOREIGN KEY(medication_id) REFERENCES medication(id))");
        db.execSQL("CREATE TABLE IF NOT EXISTS occurrence (id INTEGER PRIMARY KEY AUTOINCREMENT, plan_id INTEGER NOT NULL, occurrence_date TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'PENDING', scheduled_at TEXT NOT NULL DEFAULT '', planned_at_ms INTEGER NOT NULL DEFAULT 0, scheduled_at_ms INTEGER NOT NULL DEFAULT 0, action_at_ms INTEGER NOT NULL DEFAULT 0, actual_at_ms INTEGER NOT NULL DEFAULT 0, snooze_until_ms INTEGER NOT NULL DEFAULT 0, batch_id INTEGER NOT NULL DEFAULT 0, user_note_enc TEXT, UNIQUE(plan_id, planned_at_ms), FOREIGN KEY(plan_id) REFERENCES plan(id))");
        db.execSQL("CREATE TABLE IF NOT EXISTS event (id INTEGER PRIMARY KEY AUTOINCREMENT, occurrence_id INTEGER, event_type TEXT NOT NULL, created_at INTEGER NOT NULL, note_enc TEXT)");
        db.execSQL("CREATE TABLE IF NOT EXISTS health_item (id INTEGER PRIMARY KEY AUTOINCREMENT, kind TEXT NOT NULL, title_enc TEXT, detail_enc TEXT, source_enc TEXT, confirmed INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, deleted INTEGER NOT NULL DEFAULT 0)");
        db.execSQL("CREATE TABLE IF NOT EXISTS document (id INTEGER PRIMARY KEY AUTOINCREMENT, medication_id INTEGER, batch_id INTEGER, uri_enc TEXT, mime_type TEXT, sha256 TEXT, page_no INTEGER NOT NULL DEFAULT 1, ocr_text_enc TEXT, corrected_text_enc TEXT, chapter_enc TEXT, version_enc TEXT, manufacturer_enc TEXT, links_enc TEXT, compressed_uri_enc TEXT, compressed_sha256 TEXT, ai_raw_response_enc TEXT, structured_json_enc TEXT, prompt_version_enc TEXT, model TEXT, recognition_status TEXT NOT NULL DEFAULT 'WAITING_KEY', failure_reason_enc TEXT, request_at_ms INTEGER NOT NULL DEFAULT 0, confidence REAL NOT NULL DEFAULT 0, confirmed INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)");
        db.execSQL("CREATE TABLE IF NOT EXISTS setting (name TEXT PRIMARY KEY, value_enc TEXT, updated_at INTEGER NOT NULL)");
    }

    private static void addColumn(SQLiteDatabase db, String table, String column, String definition) { try { db.execSQL("ALTER TABLE " + table + " ADD COLUMN " + column + " " + definition); } catch (Exception ignored) { } }
    private void migratePrototypeRows(SQLiteDatabase db) {
        try {
            db.execSQL("UPDATE plan SET times_csv=time_text WHERE time_text IS NOT NULL AND time_text<>''");
            try (Cursor c = db.rawQuery("SELECT id,name,dose,stock,expiry FROM medication", null)) {
                while (c.moveToNext()) {
                    long medicationId = c.getLong(0);
                    String name = c.getString(1) == null ? "" : c.getString(1);
                    String dose = c.getString(2) == null ? "" : c.getString(2);
                    ContentValues medication = new ContentValues();
                    putEncrypted(medication, "brand_name_enc", name);
                    putEncrypted(medication, "strength_enc", dose);
                    db.update("medication", medication, "id=?", new String[]{Long.toString(medicationId)});
                    double stock = c.getDouble(3);
                    String expiry = c.getString(4) == null ? "" : c.getString(4);
                    if (stock > 0 || !expiry.isEmpty()) {
                        BatchDraft batch = new BatchDraft(); batch.quantity = stock; batch.expiryDate = expiry;
                        ContentValues values = new ContentValues(); values.put("medication_id", medicationId); values.put("quantity", batch.quantity); values.put("state", "IN_STOCK"); values.put("created_at", System.currentTimeMillis()); values.put("updated_at", System.currentTimeMillis());
                        putEncrypted(values, "lot_no_enc", ""); putEncrypted(values, "quantity_unit_enc", "片"); putEncrypted(values, "production_date_enc", ""); putEncrypted(values, "expiry_date_enc", batch.expiryDate); putEncrypted(values, "opened_date_enc", ""); putEncrypted(values, "storage_location_enc", ""); putEncrypted(values, "storage_conditions_enc", ""); putEncrypted(values, "notes_enc", "由原型库存迁移"); putEncrypted(values, "image_uri_enc", ""); db.insert("batch", null, values);
                    }
                }
            }
        } catch (Exception ignored) { }
    }
    String today() { return dayFormat.format(new java.util.Date()); }

    long addMedication(MedicationDraft draft) {
        long now = System.currentTimeMillis(); ContentValues v = new ContentValues(); v.put("name", ""); v.put("dose", ""); v.put("stock", 0); v.put("expiry", ""); v.put("created_at", Long.toString(now));
        putEncrypted(v,"generic_name_enc",draft.genericName); putEncrypted(v,"brand_name_enc",draft.brandName); putEncrypted(v,"ingredient_enc",draft.ingredients); putEncrypted(v,"strength_enc",draft.strength); putEncrypted(v,"dosage_form_enc",draft.dosageForm); putEncrypted(v,"manufacturer_enc",draft.manufacturer); putEncrypted(v,"approval_no_enc",draft.approvalNo); putEncrypted(v,"indication_enc",draft.indication); putEncrypted(v,"contraindications_enc",draft.contraindications); putEncrypted(v,"notes_enc",draft.notes); putEncrypted(v,"image_uri_enc",draft.imageUri); v.put("status",draft.status); v.put("updated_at",now); return getWritableDatabase().insertOrThrow("medication",null,v);
    }
    void updateMedication(long id, MedicationDraft draft) { ContentValues v=new ContentValues(); putEncrypted(v,"generic_name_enc",draft.genericName); putEncrypted(v,"brand_name_enc",draft.brandName); putEncrypted(v,"ingredient_enc",draft.ingredients); putEncrypted(v,"strength_enc",draft.strength); putEncrypted(v,"dosage_form_enc",draft.dosageForm); putEncrypted(v,"manufacturer_enc",draft.manufacturer); putEncrypted(v,"approval_no_enc",draft.approvalNo); putEncrypted(v,"indication_enc",draft.indication); putEncrypted(v,"contraindications_enc",draft.contraindications); putEncrypted(v,"notes_enc",draft.notes); putEncrypted(v,"image_uri_enc",draft.imageUri); v.put("status",draft.status); v.put("updated_at",System.currentTimeMillis()); getWritableDatabase().update("medication",v,"id=?",new String[]{Long.toString(id)}); }
    void setMedicationStatus(long id,String status){SQLiteDatabase db=getWritableDatabase();db.beginTransaction();try{if("ARCHIVED".equals(status))db.delete("occurrence","plan_id IN (SELECT id FROM plan WHERE medication_id=?) AND status IN ('PENDING','SNOOZED')",new String[]{Long.toString(id)});ContentValues v=new ContentValues();v.put("status",status);v.put("updated_at",System.currentTimeMillis());db.update("medication",v,"id=?",new String[]{Long.toString(id)});db.setTransactionSuccessful();}finally{db.endTransaction();}}
    void deleteMedication(long id){SQLiteDatabase db=getWritableDatabase();db.beginTransaction();try{try(Cursor c=db.rawQuery("SELECT id FROM plan WHERE medication_id=?",new String[]{Long.toString(id)})){while(c.moveToNext()){long planId=c.getLong(0);db.delete("event","occurrence_id IN (SELECT id FROM occurrence WHERE plan_id=?)",new String[]{Long.toString(planId)});db.delete("occurrence","plan_id=?",new String[]{Long.toString(planId)});}}db.delete("document","medication_id=?",new String[]{Long.toString(id)});db.delete("batch","medication_id=?",new String[]{Long.toString(id)});db.delete("plan","medication_id=?",new String[]{Long.toString(id)});db.delete("medication","id=?",new String[]{Long.toString(id)});db.setTransactionSuccessful();}finally{db.endTransaction();}}
    MedicationRow medication(long id){try(Cursor c=getReadableDatabase().rawQuery("SELECT * FROM medication WHERE id=?",new String[]{Long.toString(id)})){return c.moveToFirst()?readMedication(c):null;}}
    List<MedicationRow> medications(boolean includeArchived){List<MedicationRow> r=new ArrayList<>();String sql=includeArchived?"SELECT * FROM medication WHERE status <> 'DELETED' ORDER BY updated_at DESC":"SELECT * FROM medication WHERE status='ACTIVE' ORDER BY updated_at DESC";try(Cursor c=getReadableDatabase().rawQuery(sql,null)){while(c.moveToNext())r.add(readMedication(c));}return r;}

    long addBatch(long medId,BatchDraft d){ContentValues v=new ContentValues();v.put("medication_id",medId);v.put("quantity",d.quantity);v.put("state",d.state);v.put("created_at",System.currentTimeMillis());v.put("updated_at",System.currentTimeMillis());putEncrypted(v,"lot_no_enc",d.lotNo);putEncrypted(v,"quantity_unit_enc",d.quantityUnit);putEncrypted(v,"production_date_enc",d.productionDate);putEncrypted(v,"expiry_date_enc",d.expiryDate);putEncrypted(v,"opened_date_enc",d.openedDate);putEncrypted(v,"storage_location_enc",d.storageLocation);putEncrypted(v,"storage_conditions_enc",d.storageConditions);putEncrypted(v,"notes_enc",d.notes);putEncrypted(v,"image_uri_enc",d.imageUri);return getWritableDatabase().insertOrThrow("batch",null,v);}
    void updateBatch(long id,BatchDraft d){ContentValues v=new ContentValues();v.put("quantity",d.quantity);v.put("state",d.state);v.put("updated_at",System.currentTimeMillis());putEncrypted(v,"lot_no_enc",d.lotNo);putEncrypted(v,"quantity_unit_enc",d.quantityUnit);putEncrypted(v,"production_date_enc",d.productionDate);putEncrypted(v,"expiry_date_enc",d.expiryDate);putEncrypted(v,"opened_date_enc",d.openedDate);putEncrypted(v,"storage_location_enc",d.storageLocation);putEncrypted(v,"storage_conditions_enc",d.storageConditions);putEncrypted(v,"notes_enc",d.notes);putEncrypted(v,"image_uri_enc",d.imageUri);getWritableDatabase().update("batch",v,"id=?",new String[]{Long.toString(id)});}
    void deleteBatch(long id){getWritableDatabase().delete("batch","id=?",new String[]{Long.toString(id)});}
    List<BatchRow> batches(long medId){List<BatchRow>r=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT * FROM batch WHERE medication_id=? ORDER BY id DESC",new String[]{Long.toString(medId)})){while(c.moveToNext())r.add(readBatch(c));}return r;}
    List<BatchRow> allBatches(){List<BatchRow>r=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT * FROM batch ORDER BY medication_id,id",null)){while(c.moveToNext())r.add(readBatch(c));}return r;}

    long addPlan(long medId,PlanDraft d){return getWritableDatabase().insertOrThrow("plan",null,planValues(medId,d));}
    void updatePlan(long id,PlanDraft d){SQLiteDatabase db=getWritableDatabase();db.beginTransaction();try{db.delete("occurrence","plan_id=? AND status IN ('PENDING','SNOOZED')",new String[]{Long.toString(id)});db.update("plan",planValues(0,d),"id=?",new String[]{Long.toString(id)});db.setTransactionSuccessful();}finally{db.endTransaction();}}
    void setPlanPaused(long id,boolean paused){SQLiteDatabase db=getWritableDatabase();db.beginTransaction();try{if(paused)db.delete("occurrence","plan_id=? AND status IN ('PENDING','SNOOZED')",new String[]{Long.toString(id)});ContentValues v=new ContentValues();v.put("paused",paused?1:0);v.put("enabled",paused?0:1);db.update("plan",v,"id=?",new String[]{Long.toString(id)});db.setTransactionSuccessful();}finally{db.endTransaction();}}
    void deletePlan(long id){SQLiteDatabase db=getWritableDatabase();db.delete("occurrence","plan_id=?",new String[]{Long.toString(id)});db.delete("plan","id=?",new String[]{Long.toString(id)});}
    List<PlanRow> plans(long medId){List<PlanRow>r=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT p.*,m.brand_name_enc,m.generic_name_enc FROM plan p JOIN medication m ON m.id=p.medication_id WHERE p.medication_id=? ORDER BY p.id",new String[]{Long.toString(medId)})){while(c.moveToNext())r.add(readPlan(c));}return r;}
    List<PlanRow> allPlans(){List<PlanRow>r=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT p.*,m.brand_name_enc,m.generic_name_enc FROM plan p JOIN medication m ON m.id=p.medication_id WHERE m.status='ACTIVE'",null)){while(c.moveToNext())r.add(readPlan(c));}return r;}

    void resetPendingSchedules(long nowMs){getWritableDatabase().delete("occurrence","status='PENDING' AND scheduled_at_ms=planned_at_ms AND scheduled_at_ms>=?",new String[]{Long.toString(nowMs-2*24*60*60*1000L)});}
    void rebuildOccurrences(long nowMs,int horizonDays){SQLiteDatabase db=getWritableDatabase();long from=nowMs-2*24*60*60*1000L;long to=nowMs+horizonDays*24L*60L*60L*1000L;for(PlanRow row:allPlans()){for(Long instant:OccurrenceEngine.generate(row.schedulePlan(),from,to,ZoneId.systemDefault())){ContentValues v=new ContentValues();v.put("plan_id",row.id);v.put("occurrence_date",day(instant));v.put("status","PENDING");v.put("planned_at_ms",instant);v.put("scheduled_at_ms",instant);v.put("scheduled_at",Long.toString(instant));db.insertWithOnConflict("occurrence",null,v,SQLiteDatabase.CONFLICT_IGNORE);}}ContentValues missed=new ContentValues();missed.put("status","MISSED");missed.put("action_at_ms",nowMs);db.update("occurrence",missed,"status='PENDING' AND scheduled_at_ms<?",new String[]{Long.toString(nowMs-15*60*1000L)});}
    List<OccurrenceRow> todayOccurrences(long nowMs){long start=LocalDate.now().atStartOfDay(ZoneId.systemDefault()).toInstant().toEpochMilli();return occurrenceRange(start,start+24L*60L*60L*1000L);}
    List<OccurrenceRow> futureOccurrences(long fromMs,long toMs){return occurrenceRange(fromMs,toMs);}
    private List<OccurrenceRow> occurrenceRange(long from,long to){List<OccurrenceRow>r=new ArrayList<>();String sql="SELECT o.id,o.plan_id,o.planned_at_ms,o.scheduled_at_ms,o.status,o.action_at_ms,o.actual_at_ms,o.snooze_until_ms,o.batch_id,p.medication_id,p.dose_enc,p.meal_enc,m.brand_name_enc,m.generic_name_enc FROM occurrence o JOIN plan p ON p.id=o.plan_id JOIN medication m ON m.id=p.medication_id WHERE o.scheduled_at_ms>=? AND o.scheduled_at_ms<? ORDER BY o.scheduled_at_ms";try(Cursor c=getReadableDatabase().rawQuery(sql,new String[]{Long.toString(from),Long.toString(to)})){while(c.moveToNext())r.add(readOccurrence(c));}return r;}

    void applyOccurrenceAction(long occurrenceId,String action,long nowMs,long snoozeMs,String note){SQLiteDatabase db=getWritableDatabase();db.beginTransaction();try{OccurrenceState s=occurrenceState(db,occurrenceId);if(s==null)return;if("UNDO".equals(action)&&"TAKEN".equals(s.status)){if(s.batchId>0)adjustBatch(db,s.batchId,1);updateOccurrence(db,occurrenceId,"PENDING",nowMs,0,0,note);}else if("TAKEN".equals(action)){long batch=s.batchId>0?s.batchId:chooseBatch(db,s.medicationId);if(batch>0)adjustBatch(db,batch,-1);updateBatchLink(db,occurrenceId,batch);updateOccurrence(db,occurrenceId,"TAKEN",nowMs,nowMs,0,note);}else if("SNOOZE".equals(action)){updateOccurrence(db,occurrenceId,"SNOOZED",nowMs,0,nowMs+snoozeMs,note);}else if("SKIPPED".equals(action))updateOccurrence(db,occurrenceId,"SKIPPED",nowMs,0,0,note);else if("MISSED".equals(action))updateOccurrence(db,occurrenceId,"MISSED",nowMs,0,0,note);else if("PENDING".equals(action))updateOccurrence(db,occurrenceId,"PENDING",nowMs,0,0,note);ContentValues e=new ContentValues();e.put("occurrence_id",occurrenceId);e.put("event_type",action);e.put("created_at",nowMs);putEncrypted(e,"note_enc",note);db.insert("event",null,e);db.setTransactionSuccessful();}finally{db.endTransaction();}}

    List<HealthRow> healthItems(){List<HealthRow>r=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT * FROM health_item WHERE deleted=0 ORDER BY kind,id",null)){while(c.moveToNext())r.add(readHealth(c));}return r;}
    long saveHealth(HealthDraft d){ContentValues v=new ContentValues();v.put("kind",d.kind);v.put("confirmed",d.confirmed?1:0);v.put("created_at",System.currentTimeMillis());v.put("updated_at",System.currentTimeMillis());putEncrypted(v,"title_enc",d.title);putEncrypted(v,"detail_enc",d.detail);putEncrypted(v,"source_enc",d.source);return getWritableDatabase().insertOrThrow("health_item",null,v);}
    void updateHealth(long id,HealthDraft d){ContentValues v=new ContentValues();v.put("kind",d.kind);v.put("confirmed",d.confirmed?1:0);v.put("updated_at",System.currentTimeMillis());putEncrypted(v,"title_enc",d.title);putEncrypted(v,"detail_enc",d.detail);putEncrypted(v,"source_enc",d.source);getWritableDatabase().update("health_item",v,"id=?",new String[]{Long.toString(id)});}
    void deleteHealth(long id){getWritableDatabase().delete("health_item","id=?",new String[]{Long.toString(id)});}
    String allergiesSummary(){StringBuilder r=new StringBuilder();for(HealthRow h:healthItems())if("ALLERGY".equals(h.kind)){if(r.length()>0)r.append(",");r.append(h.title).append(" ").append(h.detail);}return r.toString();}

    long addDocument(DocumentDraft d){ContentValues v=new ContentValues();v.put("medication_id",d.medicationId);v.put("batch_id",d.batchId);v.put("mime_type",d.mimeType);v.put("sha256",d.sha256);v.put("page_no",d.pageNo);v.put("compressed_sha256",d.compressedSha256);v.put("model",d.model);v.put("recognition_status",d.status);v.put("request_at_ms",d.requestAtMs);v.put("confidence",d.confidence);v.put("confirmed",d.confirmed?1:0);v.put("created_at",System.currentTimeMillis());v.put("updated_at",System.currentTimeMillis());putEncrypted(v,"uri_enc",d.uri);putEncrypted(v,"ocr_text_enc",d.ocrText);putEncrypted(v,"corrected_text_enc",d.correctedText);putEncrypted(v,"chapter_enc",d.chapter);putEncrypted(v,"version_enc",d.version);putEncrypted(v,"manufacturer_enc",d.manufacturer);putEncrypted(v,"links_enc",d.links);putEncrypted(v,"compressed_uri_enc",d.compressedUri);putEncrypted(v,"ai_raw_response_enc",d.aiRawResponse);putEncrypted(v,"structured_json_enc",d.structuredJson);putEncrypted(v,"prompt_version_enc",d.promptVersion);putEncrypted(v,"failure_reason_enc",d.failureReason);return getWritableDatabase().insertOrThrow("document",null,v);}
    void updateDocumentAi(long id,String status,long requestAtMs,String rawResponse,String structuredJson,String visibleText,String failureReason){ContentValues v=new ContentValues();v.put("recognition_status",status);v.put("request_at_ms",requestAtMs);v.put("updated_at",System.currentTimeMillis());putEncrypted(v,"ai_raw_response_enc",rawResponse);putEncrypted(v,"structured_json_enc",structuredJson);putEncrypted(v,"ocr_text_enc",visibleText);putEncrypted(v,"failure_reason_enc",failureReason);getWritableDatabase().update("document",v,"id=?",new String[]{Long.toString(id)});}
    void updateDocumentReview(long id,String correctedText,String chapter,String version,String manufacturer,String links,boolean confirmed){ContentValues v=new ContentValues();v.put("confirmed",confirmed?1:0);v.put("recognition_status",confirmed?"CONFIRMED":"DRAFT");v.put("updated_at",System.currentTimeMillis());putEncrypted(v,"corrected_text_enc",correctedText);putEncrypted(v,"chapter_enc",chapter);putEncrypted(v,"version_enc",version);putEncrypted(v,"manufacturer_enc",manufacturer);putEncrypted(v,"links_enc",links);getWritableDatabase().update("document",v,"id=?",new String[]{Long.toString(id)});}
    List<DocumentRow> documents(String query){List<DocumentRow>r=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT * FROM document ORDER BY updated_at DESC",null)){while(c.moveToNext()){DocumentRow d=readDocument(c);if(query==null||query.trim().isEmpty()||contains(d,query.toLowerCase(Locale.ROOT)))r.add(d);}}return r;}
    void deleteDocument(long id){getWritableDatabase().delete("document","id=?",new String[]{Long.toString(id)});}
    void saveSetting(String name,String value){ContentValues v=new ContentValues();v.put("name",name);putEncrypted(v,"value_enc",value);v.put("updated_at",System.currentTimeMillis());getWritableDatabase().insertWithOnConflict("setting",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
    String setting(String name){try(Cursor c=getReadableDatabase().rawQuery("SELECT value_enc FROM setting WHERE name=?",new String[]{name})){return c.moveToFirst()?cipher.decrypt(c.getString(0)):"";}}
    void deleteSetting(String name){getWritableDatabase().delete("setting","name=?",new String[]{name});}

    private JSONArray exportOccurrences() throws Exception {JSONArray result=new JSONArray();try(Cursor c=getReadableDatabase().rawQuery("SELECT id,plan_id,occurrence_date,status,scheduled_at,planned_at_ms,scheduled_at_ms,action_at_ms,actual_at_ms,snooze_until_ms,batch_id,user_note_enc FROM occurrence",null)){while(c.moveToNext())result.put(new JSONObject().put("id",c.getLong(0)).put("planId",c.getLong(1)).put("occurrenceDate",c.getString(2)).put("status",c.getString(3)).put("scheduledAt",c.getString(4)).put("plannedAtMs",c.getLong(5)).put("scheduledAtMs",c.getLong(6)).put("actionAtMs",c.getLong(7)).put("actualAtMs",c.getLong(8)).put("snoozeUntilMs",c.getLong(9)).put("batchId",c.getLong(10)).put("userNote",cipher.decrypt(c.getString(11))));}return result;}
    private JSONArray exportEvents() throws Exception {JSONArray result=new JSONArray();try(Cursor c=getReadableDatabase().rawQuery("SELECT id,occurrence_id,event_type,created_at,note_enc FROM event",null)){while(c.moveToNext())result.put(new JSONObject().put("id",c.getLong(0)).put("occurrenceId",c.getLong(1)).put("eventType",c.getString(2)).put("createdAt",c.getLong(3)).put("note",cipher.decrypt(c.getString(4))));}return result;}
    JSONObject exportBundle() throws Exception {JSONObject root=new JSONObject();root.put("version",3);JSONArray meds=new JSONArray();for(MedicationRow m:medications(true))meds.put(m.toJson());root.put("medications",meds);JSONArray batches=new JSONArray();for(BatchRow b:allBatches())batches.put(b.toJson());root.put("batches",batches);JSONArray plans=new JSONArray();for(MedicationRow m:medications(true))for(PlanRow p:plans(m.id))plans.put(p.toJson());root.put("plans",plans);JSONArray health=new JSONArray();for(HealthRow h:healthItems())health.put(h.toJson());root.put("health",health);JSONArray docs=new JSONArray();for(DocumentRow d:documents(""))docs.put(d.toJson());root.put("documents",docs);root.put("occurrences",exportOccurrences());root.put("events",exportEvents());return root;}
    void importBundle(JSONObject root) throws Exception {clearData(false);Map<Long,Long>medMap=new HashMap<>();Map<Long,Long>batchMap=new HashMap<>();Map<Long,Long>planMap=new HashMap<>();Map<Long,Long>occurrenceMap=new HashMap<>();JSONArray meds=root.optJSONArray("medications");if(meds!=null)for(int i=0;i<meds.length();i++){JSONObject o=meds.getJSONObject(i);MedicationDraft d=MedicationDraft.fromJson(o);d.status=o.optString("status","ACTIVE");medMap.put(o.optLong("id"),addMedication(d));}JSONArray batches=root.optJSONArray("batches");if(batches!=null)for(int i=0;i<batches.length();i++){JSONObject o=batches.getJSONObject(i);Long m=medMap.get(o.optLong("medicationId"));if(m!=null)batchMap.put(o.optLong("id"),addBatch(m,BatchDraft.fromJson(o)));}JSONArray plans=root.optJSONArray("plans");if(plans!=null)for(int i=0;i<plans.length();i++){JSONObject o=plans.getJSONObject(i);Long m=medMap.get(o.optLong("medicationId"));if(m!=null)planMap.put(o.optLong("id"),addPlan(m,PlanDraft.fromJson(o)));}JSONArray health=root.optJSONArray("health");if(health!=null)for(int i=0;i<health.length();i++)saveHealth(HealthDraft.fromJson(health.getJSONObject(i)));JSONArray docs=root.optJSONArray("documents");if(docs!=null)for(int i=0;i<docs.length();i++){JSONObject o=docs.getJSONObject(i);Long m=medMap.get(o.optLong("medicationId"));Long b=batchMap.get(o.optLong("batchId"));if(m!=null){DocumentDraft d=DocumentDraft.fromJson(o);d.medicationId=m;d.batchId=b==null?0:b;addDocument(d);}}SQLiteDatabase db=getWritableDatabase();JSONArray occurrences=root.optJSONArray("occurrences");if(occurrences!=null)for(int i=0;i<occurrences.length();i++){JSONObject o=occurrences.getJSONObject(i);Long p=planMap.get(o.optLong("planId"));if(p!=null){ContentValues v=new ContentValues();v.put("plan_id",p);v.put("occurrence_date",o.optString("occurrenceDate"));v.put("status",o.optString("status","PENDING"));v.put("scheduled_at",o.optString("scheduledAt"));v.put("planned_at_ms",o.optLong("plannedAtMs"));v.put("scheduled_at_ms",o.optLong("scheduledAtMs"));v.put("action_at_ms",o.optLong("actionAtMs"));v.put("actual_at_ms",o.optLong("actualAtMs"));v.put("snooze_until_ms",o.optLong("snoozeUntilMs"));Long b=batchMap.get(o.optLong("batchId"));v.put("batch_id",b==null?0:b);putEncrypted(v,"user_note_enc",o.optString("userNote"));long id=db.insertWithOnConflict("occurrence",null,v,SQLiteDatabase.CONFLICT_IGNORE);occurrenceMap.put(o.optLong("id"),id);}}JSONArray events=root.optJSONArray("events");if(events!=null)for(int i=0;i<events.length();i++){JSONObject o=events.getJSONObject(i);Long occurrence=occurrenceMap.get(o.optLong("occurrenceId"));if(occurrence!=null){ContentValues v=new ContentValues();v.put("occurrence_id",occurrence);v.put("event_type",o.optString("eventType"));v.put("created_at",o.optLong("createdAt"));putEncrypted(v,"note_enc",o.optString("note"));db.insert("event",null,v);}}rebuildOccurrences(System.currentTimeMillis(),30);}
    void clearData(boolean deleteSettings){SQLiteDatabase db=getWritableDatabase();db.beginTransaction();try{db.delete("event",null,null);db.delete("occurrence",null,null);db.delete("document",null,null);db.delete("health_item",null,null);db.delete("batch",null,null);db.delete("plan",null,null);db.delete("medication",null,null);if(deleteSettings)db.delete("setting",null,null);db.setTransactionSuccessful();}finally{db.endTransaction();}}

    private ContentValues planValues(long medId,PlanDraft d){ContentValues v=new ContentValues();if(medId>0)v.put("medication_id",medId);v.put("type",d.type);v.put("times_csv",d.timesCsv);v.put("time_text",d.timesCsv.split(",")[0]);v.put("weekdays_mask",d.weekdaysMask);v.put("interval_hours",d.intervalHours);v.put("start_date",d.startDate);v.put("end_date",d.endDate);v.put("start_at_ms",d.startAtMs);v.put("enabled",d.enabled?1:0);v.put("paused",d.paused?1:0);putEncrypted(v,"dose_enc",d.dose);putEncrypted(v,"meal_enc",d.meal);putEncrypted(v,"notes_enc",d.notes);return v;}
    private void putEncrypted(ContentValues v,String key,String value){v.put(key,cipher.encrypt(value==null?"":value));}
    private MedicationRow readMedication(Cursor c){return new MedicationRow(c.getLong(c.getColumnIndexOrThrow("id")),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("generic_name_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("brand_name_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("ingredient_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("strength_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("dosage_form_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("manufacturer_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("approval_no_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("indication_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("contraindications_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("notes_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("image_uri_enc"))),c.getString(c.getColumnIndexOrThrow("status")));}
    private BatchRow readBatch(Cursor c){return new BatchRow(c.getLong(c.getColumnIndexOrThrow("id")),c.getLong(c.getColumnIndexOrThrow("medication_id")),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("lot_no_enc"))),c.getDouble(c.getColumnIndexOrThrow("quantity")),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("quantity_unit_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("production_date_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("expiry_date_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("opened_date_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("storage_location_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("storage_conditions_enc"))),c.getString(c.getColumnIndexOrThrow("state")),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("notes_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("image_uri_enc"))));}
    private PlanRow readPlan(Cursor c){long id=c.getLong(c.getColumnIndexOrThrow("id"));long med=c.getLong(c.getColumnIndexOrThrow("medication_id"));String brand=cipher.decrypt(c.getString(c.getColumnIndexOrThrow("brand_name_enc")));String generic=cipher.decrypt(c.getString(c.getColumnIndexOrThrow("generic_name_enc")));return new PlanRow(id,med,brand.isEmpty()?generic:brand,c.getString(c.getColumnIndexOrThrow("type")),c.getString(c.getColumnIndexOrThrow("times_csv")),c.getInt(c.getColumnIndexOrThrow("weekdays_mask")),c.getInt(c.getColumnIndexOrThrow("interval_hours")),c.getString(c.getColumnIndexOrThrow("start_date")),c.getString(c.getColumnIndexOrThrow("end_date")),c.getLong(c.getColumnIndexOrThrow("start_at_ms")),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("dose_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("meal_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("notes_enc"))),c.getInt(c.getColumnIndexOrThrow("enabled"))!=0,c.getInt(c.getColumnIndexOrThrow("paused"))!=0);}
    private OccurrenceRow readOccurrence(Cursor c){String brand=cipher.decrypt(c.getString(12));String generic=cipher.decrypt(c.getString(13));return new OccurrenceRow(c.getLong(0),c.getLong(1),c.getLong(2),c.getLong(3),c.getString(4),c.getLong(5),c.getLong(6),c.getLong(7),c.getLong(8),c.getLong(9),cipher.decrypt(c.getString(10)),cipher.decrypt(c.getString(11)),brand.isEmpty()?generic:brand);}
    private HealthRow readHealth(Cursor c){return new HealthRow(c.getLong(c.getColumnIndexOrThrow("id")),c.getString(c.getColumnIndexOrThrow("kind")),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("title_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("detail_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("source_enc"))),c.getInt(c.getColumnIndexOrThrow("confirmed"))!=0);}
    private DocumentRow readDocument(Cursor c){return new DocumentRow(c.getLong(c.getColumnIndexOrThrow("id")),c.getLong(c.getColumnIndexOrThrow("medication_id")),c.getLong(c.getColumnIndexOrThrow("batch_id")),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("uri_enc"))),c.getString(c.getColumnIndexOrThrow("mime_type")),c.getString(c.getColumnIndexOrThrow("sha256")),c.getInt(c.getColumnIndexOrThrow("page_no")),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("ocr_text_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("corrected_text_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("chapter_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("version_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("manufacturer_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("links_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("compressed_uri_enc"))),c.getString(c.getColumnIndexOrThrow("compressed_sha256")),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("ai_raw_response_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("structured_json_enc"))),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("prompt_version_enc"))),c.getString(c.getColumnIndexOrThrow("model")),c.getString(c.getColumnIndexOrThrow("recognition_status")),cipher.decrypt(c.getString(c.getColumnIndexOrThrow("failure_reason_enc"))),c.getLong(c.getColumnIndexOrThrow("request_at_ms")),c.getDouble(c.getColumnIndexOrThrow("confidence")),c.getInt(c.getColumnIndexOrThrow("confirmed"))!=0);}
    private OccurrenceState occurrenceState(SQLiteDatabase db,long id){try(Cursor c=db.rawQuery("SELECT o.status,o.batch_id,p.medication_id FROM occurrence o JOIN plan p ON p.id=o.plan_id WHERE o.id=?",new String[]{Long.toString(id)})){return c.moveToFirst()?new OccurrenceState(c.getString(0),c.getLong(1),c.getLong(2)):null;}}
    private long chooseBatch(SQLiteDatabase db,long medId){try(Cursor c=db.rawQuery("SELECT id FROM batch WHERE medication_id=? AND state='IN_STOCK' AND quantity>0 ORDER BY id LIMIT 1",new String[]{Long.toString(medId)})){return c.moveToFirst()?c.getLong(0):0;}}
    private void adjustBatch(SQLiteDatabase db,long batchId,double delta){db.execSQL("UPDATE batch SET quantity=MAX(0,quantity+?),updated_at=? WHERE id=?",new Object[]{delta,System.currentTimeMillis(),batchId});}
    private void updateBatchLink(SQLiteDatabase db,long occId,long batchId){ContentValues v=new ContentValues();v.put("batch_id",batchId);db.update("occurrence",v,"id=?",new String[]{Long.toString(occId)});}
    private void updateOccurrence(SQLiteDatabase db,long id,String status,long action,long actual,long snooze,String note){ContentValues v=new ContentValues();v.put("status",status);v.put("action_at_ms",action);v.put("actual_at_ms",actual);v.put("snooze_until_ms",snooze);putEncrypted(v,"user_note_enc",note);if(snooze>0)v.put("scheduled_at_ms",snooze);db.update("occurrence",v,"id=?",new String[]{Long.toString(id)});}
    private static String day(long ms){return new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new java.util.Date(ms));}
    private static boolean contains(DocumentRow row,String q){return row.ocrText.toLowerCase(Locale.ROOT).contains(q)||row.correctedText.toLowerCase(Locale.ROOT).contains(q)||row.chapter.toLowerCase(Locale.ROOT).contains(q)||row.version.toLowerCase(Locale.ROOT).contains(q)||row.links.toLowerCase(Locale.ROOT).contains(q);}

    static final class MedicationDraft { String genericName="",brandName="",ingredients="",strength="",dosageForm="",manufacturer="",approvalNo="",indication="",contraindications="",notes="",imageUri="",status="ACTIVE"; JSONObject toJson()throws Exception{return new JSONObject().put("genericName",genericName).put("brandName",brandName).put("ingredients",ingredients).put("strength",strength).put("dosageForm",dosageForm).put("manufacturer",manufacturer).put("approvalNo",approvalNo).put("indication",indication).put("contraindications",contraindications).put("notes",notes).put("imageUri",imageUri).put("status",status);} static MedicationDraft fromJson(JSONObject o){MedicationDraft d=new MedicationDraft();d.genericName=o.optString("genericName");d.brandName=o.optString("brandName");d.ingredients=o.optString("ingredients");d.strength=o.optString("strength");d.dosageForm=o.optString("dosageForm");d.manufacturer=o.optString("manufacturer");d.approvalNo=o.optString("approvalNo");d.indication=o.optString("indication");d.contraindications=o.optString("contraindications");d.notes=o.optString("notes");d.imageUri=o.optString("imageUri");return d;} }
    static final class MedicationRow { final long id; final String genericName,brandName,ingredients,strength,dosageForm,manufacturer,approvalNo,indication,contraindications,notes,imageUri,status; MedicationRow(long id,String genericName,String brandName,String ingredients,String strength,String dosageForm,String manufacturer,String approvalNo,String indication,String contraindications,String notes,String imageUri,String status){this.id=id;this.genericName=genericName;this.brandName=brandName;this.ingredients=ingredients;this.strength=strength;this.dosageForm=dosageForm;this.manufacturer=manufacturer;this.approvalNo=approvalNo;this.indication=indication;this.contraindications=contraindications;this.notes=notes;this.imageUri=imageUri;this.status=status;} String displayName(){return !brandName.isEmpty()?brandName:(!genericName.isEmpty()?genericName:"未命名药品");} JSONObject toJson()throws Exception{MedicationDraft d=new MedicationDraft();d.genericName=genericName;d.brandName=brandName;d.ingredients=ingredients;d.strength=strength;d.dosageForm=dosageForm;d.manufacturer=manufacturer;d.approvalNo=approvalNo;d.indication=indication;d.contraindications=contraindications;d.notes=notes;d.imageUri=imageUri;d.status=status;return d.toJson().put("id",id);} }
    static final class BatchDraft { String lotNo="",quantityUnit="片",productionDate="",expiryDate="",openedDate="",storageLocation="",storageConditions="",state="IN_STOCK",notes="",imageUri=""; double quantity; JSONObject toJson()throws Exception{return new JSONObject().put("lotNo",lotNo).put("quantity",quantity).put("quantityUnit",quantityUnit).put("productionDate",productionDate).put("expiryDate",expiryDate).put("openedDate",openedDate).put("storageLocation",storageLocation).put("storageConditions",storageConditions).put("state",state).put("notes",notes).put("imageUri",imageUri);} static BatchDraft fromJson(JSONObject o){BatchDraft d=new BatchDraft();d.quantity=o.optDouble("quantity");d.quantityUnit=o.optString("quantityUnit","片");d.lotNo=o.optString("lotNo");d.productionDate=o.optString("productionDate");d.expiryDate=o.optString("expiryDate");d.openedDate=o.optString("openedDate");d.storageLocation=o.optString("storageLocation");d.storageConditions=o.optString("storageConditions");d.state=o.optString("state","IN_STOCK");d.notes=o.optString("notes");d.imageUri=o.optString("imageUri");return d;} }
    static final class BatchRow { final long id,medicationId; final String lotNo; final double quantity; final String quantityUnit,productionDate,expiryDate,openedDate,storageLocation,storageConditions,state,notes,imageUri; BatchRow(long id,long medicationId,String lotNo,double quantity,String quantityUnit,String productionDate,String expiryDate,String openedDate,String storageLocation,String storageConditions,String state,String notes,String imageUri){this.id=id;this.medicationId=medicationId;this.lotNo=lotNo;this.quantity=quantity;this.quantityUnit=quantityUnit;this.productionDate=productionDate;this.expiryDate=expiryDate;this.openedDate=openedDate;this.storageLocation=storageLocation;this.storageConditions=storageConditions;this.state=state;this.notes=notes;this.imageUri=imageUri;} JSONObject toJson()throws Exception{return new JSONObject().put("id",id).put("medicationId",medicationId).put("lotNo",lotNo).put("quantity",quantity).put("quantityUnit",quantityUnit).put("productionDate",productionDate).put("expiryDate",expiryDate).put("openedDate",openedDate).put("storageLocation",storageLocation).put("storageConditions",storageConditions).put("state",state).put("notes",notes).put("imageUri",imageUri);} }
    static final class PlanDraft { String type="DAILY",timesCsv="08:00",startDate="",endDate="",dose="1次",meal="",notes=""; int weekdaysMask=127,intervalHours=8; long startAtMs; boolean enabled=true,paused; JSONObject toJson()throws Exception{return new JSONObject().put("type",type).put("timesCsv",timesCsv).put("weekdaysMask",weekdaysMask).put("intervalHours",intervalHours).put("startDate",startDate).put("endDate",endDate).put("startAtMs",startAtMs).put("dose",dose).put("meal",meal).put("notes",notes).put("enabled",enabled).put("paused",paused);} static PlanDraft fromJson(JSONObject o){PlanDraft d=new PlanDraft();d.type=o.optString("type","DAILY");d.timesCsv=o.optString("timesCsv","08:00");d.weekdaysMask=o.optInt("weekdaysMask",127);d.intervalHours=o.optInt("intervalHours",8);d.startDate=o.optString("startDate");d.endDate=o.optString("endDate");d.startAtMs=o.optLong("startAtMs");d.dose=o.optString("dose","1次");d.meal=o.optString("meal");d.notes=o.optString("notes");d.enabled=o.optBoolean("enabled",true);d.paused=o.optBoolean("paused",false);return d;} }
    static final class PlanRow { final long id,medicationId; final String medicationName,type,timesCsv,startDate,endDate,dose,meal,notes; final int weekdaysMask,intervalHours; final long startAtMs; final boolean enabled,paused; PlanRow(long id,long medicationId,String medicationName,String type,String timesCsv,int weekdaysMask,int intervalHours,String startDate,String endDate,long startAtMs,String dose,String meal,String notes,boolean enabled,boolean paused){this.id=id;this.medicationId=medicationId;this.medicationName=medicationName;this.type=type;this.timesCsv=timesCsv;this.weekdaysMask=weekdaysMask;this.intervalHours=intervalHours;this.startDate=startDate==null?"":startDate;this.endDate=endDate==null?"":endDate;this.startAtMs=startAtMs;this.dose=dose;this.meal=meal;this.notes=notes;this.enabled=enabled;this.paused=paused;} OccurrenceEngine.SchedulePlan schedulePlan(){OccurrenceEngine.SchedulePlan p=new OccurrenceEngine.SchedulePlan();p.id=id;p.type=type;p.timesCsv=timesCsv;p.weekdaysMask=weekdaysMask;p.intervalHours=intervalHours;p.startDate=startDate;p.endDate=endDate;p.startAtMs=startAtMs;p.enabled=enabled;p.paused=paused;return p;} JSONObject toJson()throws Exception{PlanDraft d=new PlanDraft();d.type=type;d.timesCsv=timesCsv;d.weekdaysMask=weekdaysMask;d.intervalHours=intervalHours;d.startDate=startDate;d.endDate=endDate;d.startAtMs=startAtMs;d.dose=dose;d.meal=meal;d.notes=notes;d.enabled=enabled;d.paused=paused;return d.toJson().put("id",id).put("medicationId",medicationId);} }
    static final class OccurrenceRow { final long id,planId,plannedAtMs,scheduledAtMs,actionAtMs,actualAtMs,snoozeUntilMs,batchId,medicationId; final String status,dose,meal,medicationName; OccurrenceRow(long id,long planId,long plannedAtMs,long scheduledAtMs,String status,long actionAtMs,long actualAtMs,long snoozeUntilMs,long batchId,long medicationId,String dose,String meal,String medicationName){this.id=id;this.planId=planId;this.plannedAtMs=plannedAtMs;this.scheduledAtMs=scheduledAtMs;this.status=status;this.actionAtMs=actionAtMs;this.actualAtMs=actualAtMs;this.snoozeUntilMs=snoozeUntilMs;this.batchId=batchId;this.medicationId=medicationId;this.dose=dose;this.meal=meal;this.medicationName=medicationName;} }
    static final class HealthDraft { String kind="CONDITION",title="",detail="",source="用户输入"; boolean confirmed; JSONObject toJson()throws Exception{return new JSONObject().put("kind",kind).put("title",title).put("detail",detail).put("source",source).put("confirmed",confirmed);} static HealthDraft fromJson(JSONObject o){HealthDraft d=new HealthDraft();d.kind=o.optString("kind");d.title=o.optString("title");d.detail=o.optString("detail");d.source=o.optString("source");d.confirmed=o.optBoolean("confirmed");return d;} }
    static final class HealthRow { final long id; final String kind,title,detail,source; final boolean confirmed; HealthRow(long id,String kind,String title,String detail,String source,boolean confirmed){this.id=id;this.kind=kind;this.title=title;this.detail=detail;this.source=source;this.confirmed=confirmed;} JSONObject toJson()throws Exception{HealthDraft d=new HealthDraft();d.kind=kind;d.title=title;d.detail=detail;d.source=source;d.confirmed=confirmed;return d.toJson().put("id",id);} }
    static final class DocumentDraft { long medicationId,batchId,requestAtMs; String uri="",mimeType="",sha256="",ocrText="",correctedText="",chapter="",version="",manufacturer="",links="",compressedUri="",compressedSha256="",aiRawResponse="",structuredJson="",promptVersion="",model="deepseek-flash",status="WAITING_KEY",failureReason=""; int pageNo=1; double confidence; boolean confirmed; static DocumentDraft fromJson(JSONObject o){DocumentDraft d=new DocumentDraft();d.uri=o.optString("uri");d.mimeType=o.optString("mimeType");d.sha256=o.optString("sha256");d.pageNo=o.optInt("pageNo",1);d.ocrText=o.optString("ocrText");d.correctedText=o.optString("correctedText");d.chapter=o.optString("chapter");d.version=o.optString("version");d.manufacturer=o.optString("manufacturer");d.links=o.optString("links");d.compressedUri=o.optString("compressedUri");d.compressedSha256=o.optString("compressedSha256");d.aiRawResponse=o.optString("aiRawResponse");d.structuredJson=o.optString("structuredJson");d.promptVersion=o.optString("promptVersion");d.model=o.optString("model","deepseek-flash");d.status=o.optString("status","LEGACY");d.failureReason=o.optString("failureReason");d.requestAtMs=o.optLong("requestAtMs");d.confidence=o.optDouble("confidence",0);d.confirmed=o.optBoolean("confirmed",false);return d;} }
    static final class DocumentRow { final long id,medicationId,batchId,requestAtMs; final String uri,mimeType,sha256; final int pageNo; final String ocrText,correctedText,chapter,version,manufacturer,links,compressedUri,compressedSha256,aiRawResponse,structuredJson,promptVersion,model,recognitionStatus,failureReason; final double confidence; final boolean confirmed; DocumentRow(long id,long medicationId,long batchId,String uri,String mimeType,String sha256,int pageNo,String ocrText,String correctedText,String chapter,String version,String manufacturer,String links,String compressedUri,String compressedSha256,String aiRawResponse,String structuredJson,String promptVersion,String model,String recognitionStatus,String failureReason,long requestAtMs,double confidence,boolean confirmed){this.id=id;this.medicationId=medicationId;this.batchId=batchId;this.uri=uri;this.mimeType=mimeType;this.sha256=sha256;this.pageNo=pageNo;this.ocrText=ocrText;this.correctedText=correctedText;this.chapter=chapter;this.version=version;this.manufacturer=manufacturer;this.links=links;this.compressedUri=compressedUri;this.compressedSha256=compressedSha256;this.aiRawResponse=aiRawResponse;this.structuredJson=structuredJson;this.promptVersion=promptVersion;this.model=model;this.recognitionStatus=recognitionStatus;this.failureReason=failureReason;this.requestAtMs=requestAtMs;this.confidence=confidence;this.confirmed=confirmed;} JSONObject toJson()throws Exception{return new JSONObject().put("id",id).put("medicationId",medicationId).put("batchId",batchId).put("uri",uri).put("mimeType",mimeType).put("sha256",sha256).put("pageNo",pageNo).put("ocrText",ocrText).put("correctedText",correctedText).put("chapter",chapter).put("version",version).put("manufacturer",manufacturer).put("links",links).put("compressedUri",compressedUri).put("compressedSha256",compressedSha256).put("aiRawResponse",aiRawResponse).put("structuredJson",structuredJson).put("promptVersion",promptVersion).put("model",model).put("status",recognitionStatus).put("failureReason",failureReason).put("requestAtMs",requestAtMs).put("confidence",confidence).put("confirmed",confirmed);} }
    private static final class OccurrenceState { final String status; final long batchId,medicationId; OccurrenceState(String status,long batchId,long medicationId){this.status=status;this.batchId=batchId;this.medicationId=medicationId;} }
}
